[build-system]
requires = ["uv_build>=0.11.31,<0.12.0"]
build-backend = "uv_build"

[project]
name = "comstock-processor"
version = "0.1.0"
description = "A tool to download and process ComStock data."
authors = [{ name = "Nicholas Long" }]
license = "BSD-3-Clause"
requires-python = ">=3.12"
dependencies = [
    "pandas>=3.0.5",
    "requests>=2.32.5",
    "geopandas>=1.1.4",
    "tqdm>=4.69.0",
    "seaborn>=0.13.2",
    "matplotlib>=3.11.1",
    # although not called directly, these are
    # needed for processing parquet files
    "fastparquet>=2026.5.0",
    "pyarrow>=25.0.0",
    # needed to read ResStock's measure_name_crosswalk .xlsx file
    "openpyxl>=3.1.5",
]

[dependency-groups]
dev = [
    "pytest>=9.1.1",
    "pytest-mock>=3.15.1",
    "mypy>=2.3.0",
    "pre-commit>=4.6.1",
    "ipykernel>=7.3.0",
    "jupyter>=1.1.1",
    "nbformat>=5.10.4",
]

[tool.uv]
package = true

[tool.mypy]
python_version = "3.12"
files = [
    "src/comstock_processor/",
    "tests/",
]
ignore_missing_imports = true
strict = true

[[tool.mypy.overrides]]
module = "tests.*"
disallow_untyped_defs = false

[tool.pytest.ini_options]
minversion = "6.0"
addopts = [
    "-ra",
    "-q",
    "--strict-markers",
    "--disable-warnings"
]
testpaths = ["tests"]
markers = [
    "integration: marks tests as integration tests that download data",
    "unit: marks tests as fast unit tests"
]
filterwarnings = [
    "ignore::DeprecationWarning",
    "ignore::PendingDeprecationWarning"
]
